### PR TITLE
feat: YaruSplitButton

### PR DESCRIPTION
**Pull request by Feichtmeier**
Either a list of poupmenuitems needs to be provided or an onOptionButtonPressed callback

Question was if the list of options/callback should still be active if the main action is null/disabled?

Ref #912

### CODE REVIEW

**Review by Jupi007 — APPROVED** [review]
LGTM :+1: 
But I think it would be better to have a more generic implementation: something like a YaruGroupedButton widget, which could be more versatile :thinking:

**Comment by Feichtmeier** [comment]
> LGTM 👍 But I think it would be better to have a more generic implementation: something like a YaruGroupedButton widget, which could be more versatile 🤔

what do you mean? like the position of the dropdown?

**Comment by Jupi007** [comment]
In my idea, we could add as much item as we want, with any role, just like this: https://getbootstrap.com/docs/4.0/components/button-group/#nesting

**Comment by Feichtmeier** [comment]
> In my idea, we could add as much item as we want, with any role, just like this: https://getbootstrap.com/docs/4.0/components/button-group/#nesting

hm I don't know if the positioning of the menu will work then but maybe its totally possible
how about we add both: this specialized widget and that one?

**Comment by Jupi007** [comment]
Yes, and this specialized widget could be a shortcut to the generic grouped button one.
This can be done in another PR :)

**Comment by Feichtmeier** [comment]
ok as requested I made the menu right aligned
also removed the default width so the width is just how wide the menu wants to be
I left the width parameter so when one wants to set it its still possible

grafik
grafik
grafik

**Comment by Feichtmeier** [comment]
Merged it with ref instead of fixes so we can work on it more if we want to

**Comment by spydon** [comment]
Looks great! :heart_eyes:

**Pull request merged**
