### PR TITLE
fix: high contrast themes: ListTile selected state is not distinguishable from non-selected state

### LINKED ISSUE #939: high contrast themes: `ListTile` selected state is not distinguishable from non-selected state
For the high contrast themes the `primaryColor` defaults to either black or white, so that selected `ListTile`s are visually indistinguishable from non-selected ones.

| | Light | Dark |
| - | - | - |
| Normal | Screenshot From 2024-10-25 14-03-07 | Screenshot From 2024-10-25 14-03-24 |
| High Contrast | Screenshot From 2024-10-25 14-02-18 | Screenshot From 2024-10-25 14-02-51 |

Minimal example:
```dart
import 'package:flutter/material.dart';
import 'package:yaru/yaru.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return YaruTheme(
      builder: (context, yaru, child) {
        return MaterialApp(
          theme: yaru.theme,
          darkTheme: yaru.darkTheme,
          highContrastTheme: yaruHighContrastLight,
          highContrastDarkTheme: yaruHighContrastDark,
          title: 'Flutter Demo',
          home: Scaffold(
            body: ListView(
              children: const [
                ListTile(
                  selected: true,
                  title: Text('selected tile'),
                ),
                ListTile(
                  selected: false,
                  title: Text('unselected tile'),
                )
              ],
            ),
          ),
        );
      },
    );
  }
}

```

### LINKED ISSUE #940: [BUG] Error Building Yaru App
When tried to build Yaru Flutter app, I'm getting error for the code below 

**Code:**
```dart

import 'package:flutter/material.dart';
import 'package:yaru/yaru.dart';

Future<void> main() async {
  await YaruWindowTitleBar.ensureInitialized();
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return YaruTheme(builder: (context, yaru, child) {
      return MaterialApp(
        debugShowCheckedModeBanner: false, // <-------------
        theme: yaru.theme, // <-----------
        darkTheme: yaru.darkTheme, // <-------------
        home: Scaffold(
          appBar: const YaruWindowTitleBar(), // <-------------
        ),
      );
    });
  }
}
```

**Error:**
```dart
Launching lib/main.dart on Linux in debug mode...
ERROR: ../../../../.pub-cache/hosted/pub.dev/animated_vector-0.2.1/lib/src/data.dart:233:35: Error: The method 'withValues' isn't defined for the class 'Color'.
ERROR:  - 'Color' is from 'dart:ui'.
ERROR: Try correcting the name to the name of an existing method, or defining a method named 'withValues'.
ERROR:           const Color(0xFFFFFFFF).withValues(alpha: evaluated.alpha),
ERROR:                                   ^^^^^^^^^^
ERROR: ../../../../.pub-cache/hosted/pub.dev/animated_vector-0.2.1/lib/src/data.dart:521:33: Error: The method 'withValues' isn't defined for the class 'Color'.
ERROR:  - 'Color' is from 'dart:ui'.
ERROR: Try correcting the name to the name of an existing method, or defining a method named 'withValues'.
ERROR:           ..color = strokeColor.withValues(
ERROR:                                 ^^^^^^^^^^
ERROR: ../../../../.pub-cache/hosted/pub.dev/animated_vector-0.2.1/lib/src/data.dart:522:32: Error: The getter 'a' isn't defined for the class 'Color'.
ERROR:  - 'Color' is from 'dart:ui'.
ERROR: Try correcting the name to the name of an existing getter, or defining a getter or field named 'a'.
ERROR:             alpha: strokeColor.a * evaluated.strokeAlpha!,
ERROR:                                ^
ERROR: ../../../../.pub-cache/hosted/pub.dev/animated_vector-0.2.1/lib/src/data.dart:535:23: Error: The method 'withValues' isn't defined for the class 'Color'.
ERROR:  - 'Color' is from 'dart:ui'.
ERROR: Try correcting the name to the name of an existing method, or defining a method named 'withValues'.
ERROR:             fillColor.withValues(alpha: fillColor.a * evaluated.fillAlpha!),
ERROR:                       ^^^^^^^^^^
ERROR: ../../../../.pub-cache/hosted/pub.dev/animated_vector-0.2.1/lib/src/data.dart:535:51: Error: The getter 'a' isn't defined for the class 'Color'.
ERROR:  - 'Color' is from 'dart:ui'.
ERROR: Try correcting the name to the name of an existing getter, or defining a getter or field named 'a'.
ERROR:             fillColor.withValues(alpha: fillColor.a * evaluated.fillAlpha!),
ERROR:                                                   ^
ERROR: ../../../../.pub-cache/hosted/pub.dev/animated_vector-0.2.1/lib/src/shapeshifter.dart:769:13: Error: The getter 'a' isn't defined for the class 'Color'.
ERROR:  - 'Color' is from 'dart:ui'.
ERROR: Try correcting the name to the name of an existing getter, or defining a getter or field named 'a'.
ERROR:   if (color.a == 0xFF) return "#${radixString.substring(2)}";
ERROR:             ^
ERROR: Target kernel_snapshot_program failed: Exception
Building Linux application...                                           
Error: Build process failed
```

### PR DESCRIPTION
**Pull request by Feichtmeier**
grafik

now the improved high contrast list tiles:

Bildschirmfoto 2024-10-27 um 12 03 30

grafik

Fixes #939

Bonus:

Fixes #940

### CODE REVIEW

**Comment by Feichtmeier** [comment]
okay it works, but we have a new analyzer problem

@HrX03 @Jupi007 

```
   info • The import of 'package:animated_vector/animated_vector.dart' is unnecessary because all of the used elements are also provided by the import of 'package:animated_vector_annotations/animated_vector_annotations.dart' • lib/src/icons/icons_widgets/yaru_animated_icons.dart:1:8 • unnecessary_import
   info • The import of 'package:flutter/widgets.dart' is unnecessary because all of the used elements are also provided by the import of 'package:animated_vector_annotations/animated_vector_annotations.dart' • lib/src/icons/icons_widgets/yaru_animated_icons.dart:3:8 • unnecessary_import
```

when I remove it yaru_animated_icons.dart is missing the import O.o
whats happening?

**Comment by dvd-bnc** [comment]
> okay it works, but we have a new analyzer problem
> 
> @HrX03 @Jupi007 
> 
> ```
>    info • The import of 'package:animated_vector/animated_vector.dart' is unnecessary because all of the used elements are also provided by the import of 'package:animated_vector_annotations/animated_vector_annotations.dart' • lib/src/icons/icons_widgets/yaru_animated_icons.dart:1:8 • unnecessary_import
>    info • The import of 'package:flutter/widgets.dart' is unnecessary because all of the used elements are also provided by the import of 'package:animated_vector_annotations/animated_vector_annotations.dart' • lib/src/icons/icons_widgets/yaru_animated_icons.dart:3:8 • unnecessary_import
> ```
> 
> when I remove it yaru_animated_icons.dart is missing the import O.o
> whats happening?

I moved all of the required imports for generated files into the animated_vector_annotations file, I think the yaru lib will need to update to not include other stuff inside those files

**Comment by Jupi007** [comment]
<del>Weird, I can't reproduce the analyzing error locally using your branch 🤔</del>
Okay, I reproduced it

**Comment by Jupi007** [comment]
Yeah, it looks like you just need to drop `animated_vector.dart` and `widgets.dart`:
```diff
- import 'package:animated_vector/animated_vector.dart';
import 'package:animated_vector_annotations/animated_vector_annotations.dart';
- import 'package:flutter/widgets.dart';
```

**Comment by Feichtmeier** [comment]
> Yeah, it looks like you just need to drop `animated_vector.dart` and `widgets.dart`:
> 
> ```diff
> - import 'package:animated_vector/animated_vector.dart';
> import 'package:animated_vector_annotations/animated_vector_annotations.dart';
> - import 'package:flutter/widgets.dart';
> ```

no I dont think this works : D

now I got 777 x Undefined class 'AnimatedVectorData'.
Try changing the name to the name of an existing class, or creating a class with the name 'AnimatedVectorData'.

**Comment by dvd-bnc** [comment]
> > Yeah, it looks like you just need to drop `animated_vector.dart` and `widgets.dart`:
> > 
> > ```diff
> > - import 'package:animated_vector/animated_vector.dart';
> > import 'package:animated_vector_annotations/animated_vector_annotations.dart';
> > - import 'package:flutter/widgets.dart';
> > ```
> 
> no I dont think this works : D
> 
> now I got 777 x Undefined class 'AnimatedVectorData'.
> Try changing the name to the name of an existing class, or creating a class with the name 'AnimatedVectorData'.
> 

I have just checked and the member is exported from the file, did you update every animated_vector dep and ran pub get/upgrade? Also try restarting the analyzer, I'm sure the member is exported

**Comment by Feichtmeier** [comment]
> > > Yeah, it looks like you just need to drop `animated_vector.dart` and `widgets.dart`:
> > > ```diff
> > > - import 'package:animated_vector/animated_vector.dart';
> > > import 'package:animated_vector_annotations/animated_vector_annotations.dart';
> > > - import 'package:flutter/widgets.dart';
> > > ```
> > 
> > 
> > no I dont think this works : D
> > now I got 777 x Undefined class 'AnimatedVectorData'.
> > Try changing the name to the name of an existing class, or creating a class with the name 'AnimatedVectorData'.
> 
> I have just checked and the member is exported from the file, did you update every animated_vector dep and ran pub get/upgrade? Also try restarting the analyzer, I'm sure the member is exported

jeeez, sorry.

**Review by Jupi007 — APPROVED** [review]
LGTM 👍

**Comment by Feichtmeier** [comment]
the goldens test passes locally, we need the nightly for this I think so this can be ignored

**Pull request merged**
