### PR TITLE
feat(example): monospace text style in `_CodeDialog`

### PR DESCRIPTION
**Pull request by andrew-ares**
Use monospaced style in `_CodeDialog` to improve readability.

yaru_example_2024_12_18@2x

### CODE REVIEW

**Comment by Jupi007** [comment]
Great 👍
But maybe should we import the ubuntu mono font into this project directly.
Byw this could be helpful for the datetime picker.
Wdyt @Feichtmeier ?

**Comment by andrew-ares** [comment]
Please take another look

**Comment by Feichtmeier** [comment]
I think the font adding in the yaru pubspec is enough, the example should then use the font by using the yaru package from path

**Comment by Jupi007** [comment]
Yes I think you're right @Feichtmeier

**Review by Feichtmeier — APPROVED** [review]

**Pull request merged**
