### PR TITLE
chore: restructure directories and remove duplicated fonts

### PR DESCRIPTION
**Pull request by Feichtmeier**
After the repo merge I postponed the reorganisation but I think it is overdue.
Also I found that we have duplicates of the ubuntu font.... which should be quite bad for the package size

@Jupi007 could you check if the icon generation still works ?

### CODE REVIEW

**Review by spydon — APPROVED** [review]
Lgtm!

**Comment by Jupi007** [comment]
@Feichtmeier You need to change this line:

https://github.com/ubuntu/yaru.dart/blob/f29d45e555f522dbd43888b0f180db646022bc25/pubspec.yaml#L69

```diff
-  output_class_file: "lib/src/yaru_icons.dart"
+  output_class_file: "lib/src/icons/yaru_icons.dart"
```

**Comment by Feichtmeier** [comment]
THanks!!

**Comment by Feichtmeier** [comment]
@Jupi007 could you double check please

**Review by Jupi007 — APPROVED** [review]
LGTM :+1: 
Thanks a lot @Feichtmeier 
This is way cleaner!

**Pull request merged**
